version: '3.9'

services:
  booking-core_api-gateway:
    container_name: 'booking-core_api-gateway'
    build: .
    ports:
      - 8888:8888
      - 5555:5555
    networks:
      - booking-core
    environment:
      _JAVA_OPTIONS: >
        -Xdebug
        -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5555
networks:
  booking-core:
    name: booking-core
    driver: bridge